### ISSUE TITLE
Didn't pass external variable to the workflow it run

### ISSUE THREAD

**Issue by mackoj** [bitrise-steplib/steps-bitrise-run#4]
Hi,

Below I customize **BITRISE_RUN_EXTERNAL_VARIABLE** to the value **External** but in the final workflow I can't get this value.
On the _remote_(bitrise.yml on bitrise.com) I have set this value to **Remote**
On the _local_(bitrise.yml on the repo) I have set this value to **Local**
From the curl I have set it to **External**.

Since I did enable replace variable inputs I should have received **External** instead of **Local**.

```
curl https://app.bitrise.io/app/xxx/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"xxx"},"build_params":{"branch":"master","workflow_id":"test","environments":[{"mapped_to":"BITRISE_RUN_EXTERNAL_VARIABLE","value":"External","is_expand":true}]},"triggered_by":"curl"}'
```

https://app.bitrise.io/build/454ba91c690efd48

I think that `bitrise-run` should send all externally defined variable to the bitrise run that it start in order to allow customization.

Thanks

**Comment by mackoj** [comment]
Hi @bitce,

I have made a sample app that show the issue => https://github.com/mackoj/bitriseTestApp.

From my understanding it should have been `External` since the variable value can be changed ? And this `External` value should be passed to the **bitrise run** instead of being rewrite.

How can I have a variable with a default value that I can update from the curl request/Advanced tab ?
Can this variable default be set in the bitrise.yml file that is in the repo ?

Thanks,

**Comment by mackoj** [comment]
Hi @bitce,

I have made a sample app that show the issue => https://github.com/mackoj/bitriseTestApp.

From my understanding it should have been `External` since the variable value can be changed ? And this `External` value should be passed to the **bitrise run** instead of being rewrite.

How can I have a variable with a default value that I can update from the curl request/Advanced tab ?
Can this variable default be set in the bitrise.yml file that is in the repo ?

When I print the variable before the **bitrise run** I have **Remote** => https://app.bitrise.io/build/6185961018ebd3a5

Thanks,

**Comment by bitce** [comment]
Hi @mackoj! Oh I see now that bitrise run is what's exposing these. Well the values can be overwritten, but not by setting them on the advanced tab - due to the processing order. However, you can do this through the API: https://discuss.bitrise.io/t/how-to-override-environment-variables-through-the-build-trigger-api/191
